import Link from "next/link";
import { createHash } from "node:crypto";
import { db } from "@/lib/db";
import { getCurrentSession } from "@/lib/auth/session";
import { acceptInviteAction } from "@/app/actions/domain";
import Image from "next/image";
import { ThemeSwitcher } from "@/components/shared/theme-switcher";

export default async function InvitePage({params}:{params:Promise<{token:string}>}){const{token}=await params;const session=await getCurrentSession();const tokenHash=createHash("sha256").update(token).digest("hex");const invite=await db.workspaceInvite.findUnique({where:{tokenHash},include:{workspace:true}});const valid=Boolean(invite&&!invite.acceptedAt&&!invite.revokedAt&&invite.expiresAt>new Date());return <main className="grid min-h-screen place-items-center px-5"><div className="relative w-full max-w-md rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-8 text-center shadow-xl"><div className="absolute right-4 top-4"><ThemeSwitcher /></div><Image src="/branding/taskflow-v1.1/taskflow-app-icon.svg" alt="" width={48} height={48} className="mx-auto size-12" /><h1 className="mt-5 text-2xl font-semibold">Zaproszenie do TaskFlow</h1>{valid?<><p className="mt-3 text-[var(--muted)]">Dołączasz do przestrzeni <strong className="text-[var(--foreground)]">{invite!.workspace.name}</strong>.</p>{session?<form action={acceptInviteAction.bind(null,token)} className="mt-6"><button className="w-full rounded-xl bg-[var(--accent)] px-4 py-3 font-semibold text-[var(--on-accent)]">Akceptuj zaproszenie</button></form>:<div className="mt-6 grid gap-2"><Link href={`/login?callbackUrl=${encodeURIComponent(`/invite/${token}`)}`} className="rounded-xl bg-[var(--accent)] px-4 py-3 font-semibold text-[var(--on-accent)]">Zaloguj się</Link><Link href={`/register?invite=${encodeURIComponent(token)}`} className="rounded-xl border border-[var(--border-strong)] px-4 py-3 font-semibold">Utwórz konto</Link></div>}</>:<><p className="mt-3 text-[var(--muted)]">Ten link wygasł, został wykorzystany albo unieważniony.</p><Link href="/" className="mt-6 inline-block text-[var(--accent-ink)]">Wróć na stronę główną</Link></>}</div></main>}
