import { ActionForm } from "@/components/shared/action-form";
import Link from "next/link";
import { ExternalLink, Trash2, X } from "lucide-react";
import type { Prisma } from "@/generated/prisma/client";
import type { WorkspaceRole } from "@/generated/prisma/enums";
import { addCommentAction, addLinkAction, createLabelAction, deleteTaskAction, removeLinkAction, updateTaskAction } from "@/app/actions/domain";
import { toDateOnly } from "@/lib/date-only";
import { ConfirmSubmit } from "@/components/shared/confirm-submit";

type TaskPanelTask = Prisma.TaskGetPayload<{ include: { assignees: true; labels: true; comments: { include: { author: true } }; links: true; activities: { include: { actor: true } } } }>;
type WorkspaceMemberWithUser = Prisma.WorkspaceMemberGetPayload<{ include: { user: true } }>;
type TaskPanelProps = { workspaceId: string; projectId: string; task: TaskPanelTask; members: WorkspaceMemberWithUser[]; labels: Prisma.LabelModel[]; currentUserId: string; role: WorkspaceRole; readOnly: boolean };

export function TaskPanel({ workspaceId, projectId, task, members, labels, currentUserId, role, readOnly }: TaskPanelProps) {
  const canDelete = task.createdById === currentUserId || ["OWNER", "ADMIN"].includes(role);
  return <div className="fixed inset-0 z-40 flex justify-end bg-black/20"><Link aria-label="Zamknij szczegóły" href={`/w/${workspaceId}/projects/${projectId}`} className="absolute inset-0" /><aside role="dialog" aria-modal="true" aria-labelledby="task-title" className="relative h-full w-full overflow-y-auto bg-white p-5 shadow-2xl sm:max-w-xl sm:p-7"><div className="flex items-center justify-between"><p className="text-sm font-medium text-orange-600">Szczegóły zadania</p><Link href={`/w/${workspaceId}/projects/${projectId}`} aria-label="Zamknij" className="rounded-lg p-2 hover:bg-[#f5f5f2]"><X size={19} /></Link></div>
    <ActionForm action={updateTaskAction.bind(null, workspaceId, task.id)} className="mt-6 space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">Tytuł</span><input id="task-title" disabled={readOnly} required name="title" defaultValue={task.title} maxLength={160} className="w-full rounded-xl border border-[#deded9] px-3 py-2.5 text-lg font-semibold disabled:bg-[#fafaf8]" /></label><label className="block"><span className="mb-2 block text-sm font-medium">Opis</span><textarea disabled={readOnly} name="description" defaultValue={task.description || ""} maxLength={10000} rows={5} className="w-full rounded-xl border border-[#deded9] px-3 py-2.5 disabled:bg-[#fafaf8]" /></label><div className="grid grid-cols-2 gap-3"><SelectField disabled={readOnly} label="Status" name="status" value={task.status} options={[['TODO','Do zrobienia'],['IN_PROGRESS','W trakcie'],['DONE','Ukończone']]} /><SelectField disabled={readOnly} label="Priorytet" name="priority" value={task.priority} options={[['LOW','Niski'],['MEDIUM','Średni'],['HIGH','Wysoki'],['URGENT','Pilny']]} /></div><label className="block"><span className="mb-2 block text-sm font-medium">Termin</span><input disabled={readOnly} type="date" name="dueDate" defaultValue={toDateOnly(task.dueDate) || ""} className="w-full rounded-xl border border-[#deded9] px-3 py-2.5 disabled:bg-[#fafaf8]" /></label><fieldset disabled={readOnly}><legend className="mb-2 text-sm font-medium">Przypisani</legend><div className="flex flex-wrap gap-2">{members.map((member) => <label key={member.user.id} className="flex items-center gap-2 rounded-xl border border-[#e8e8e3] px-3 py-2 text-sm"><input type="checkbox" name="assigneeIds" value={member.user.id} defaultChecked={task.assignees.some((a) => a.userId === member.user.id)} />{member.user.name}</label>)}</div></fieldset><fieldset disabled={readOnly}><legend className="mb-2 text-sm font-medium">Etykiety</legend><div className="flex flex-wrap gap-2">{labels.map((label) => <label key={label.id} className="flex items-center gap-2 rounded-xl border border-[#e8e8e3] px-3 py-2 text-sm"><input type="checkbox" name="labelIds" value={label.id} defaultChecked={task.labels.some((item) => item.labelId === label.id)} /><span className="size-2 rounded-full" style={{ background: label.color }} />{label.name}</label>)}</div></fieldset>{!readOnly && <button className="w-full rounded-xl bg-orange-500 px-4 py-3 font-semibold text-white">Zapisz zmiany</button>}</ActionForm>
    {!readOnly && <details className="mt-5 rounded-xl border border-[#ececea] p-4"><summary className="cursor-pointer font-medium">Nowa etykieta</summary><ActionForm action={createLabelAction.bind(null, workspaceId)} resetOnSuccess className="mt-3 flex gap-2"><input name="name" required maxLength={40} placeholder="Nazwa" className="min-w-0 flex-1 rounded-lg border border-[#deded9] px-3 py-2" /><input aria-label="Kolor" type="color" name="color" defaultValue="#F97316" className="h-10 w-12" /><button className="rounded-lg bg-[#252525] px-3 text-sm text-white">Dodaj</button></ActionForm></details>}
    <Section title={`Komentarze (${task.comments.length})`}>{task.comments.map((comment) => <div key={comment.id} className="rounded-xl bg-[#fafaf8] p-3"><p className="text-xs font-semibold">{comment.author.name}</p><p className="mt-1 whitespace-pre-wrap text-sm">{comment.body}</p></div>)}{!readOnly && <ActionForm action={addCommentAction.bind(null, workspaceId, task.id)} resetOnSuccess className="flex gap-2"><input required maxLength={2000} name="body" placeholder="Dodaj komentarz…" className="min-w-0 flex-1 rounded-xl border border-[#deded9] px-3 py-2" /><button className="rounded-xl bg-[#252525] px-3 text-sm text-white">Dodaj</button></ActionForm>}</Section>
    <Section title={`Linki (${task.links.length})`}>{task.links.map((link) => <div key={link.id} className="flex items-center gap-2 rounded-xl bg-[#fafaf8] p-3"><a target="_blank" rel="noopener noreferrer" href={link.url} className="min-w-0 flex-1 truncate text-sm font-medium text-orange-700">{link.title} <ExternalLink className="inline" size={13} /></a>{!readOnly && <form action={removeLinkAction.bind(null, workspaceId, link.id)}><button aria-label="Usuń link" className="text-red-600"><Trash2 size={15} /></button></form>}</div>)}{!readOnly && <ActionForm action={addLinkAction.bind(null, workspaceId, task.id)} resetOnSuccess className="grid gap-2"><input required maxLength={160} name="title" placeholder="Nazwa linku" className="rounded-xl border border-[#deded9] px-3 py-2" /><div className="flex gap-2"><input required type="url" name="url" placeholder="https://…" className="min-w-0 flex-1 rounded-xl border border-[#deded9] px-3 py-2" /><button className="rounded-xl bg-[#252525] px-3 text-sm text-white">Dodaj</button></div></ActionForm>}</Section>
    <Section title="Ostatnia aktywność">{task.activities.map((activity) => <p key={activity.id} className="border-l-2 border-orange-200 pl-3 text-sm"><span className="font-medium">{activity.actor.name}</span> · {activity.action.toLowerCase().replaceAll("_", " ")}</p>)}</Section>
    {!readOnly && canDelete && <form action={deleteTaskAction.bind(null, workspaceId, task.id)} className="mt-8"><ConfirmSubmit message="Usunąć to zadanie? Tej operacji nie można cofnąć." className="flex items-center gap-2 text-sm font-medium text-red-600"><Trash2 size={16} />Usuń zadanie</ConfirmSubmit></form>}
  </aside></div>;
}

function SelectField({ label, name, value, options, disabled }: { label: string; name: string; value: string; options: string[][]; disabled: boolean }) { return <label><span className="mb-2 block text-sm font-medium">{label}</span><select disabled={disabled} name={name} defaultValue={value} className="w-full rounded-xl border border-[#deded9] px-3 py-2.5 disabled:bg-[#fafaf8]">{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-8"><h2 className="mb-3 font-semibold">{title}</h2><div className="space-y-3">{children}</div></section>; }
