import { ActionForm } from "@/components/shared/action-form";
/* eslint-disable @typescript-eslint/no-explicit-any -- Local render helpers consume Prisma relation payloads. */
import Link from "next/link";
import { Activity, Archive, Columns3, Link2, List, Users } from "lucide-react";
import { db } from "@/lib/db";
import { requireProjectAccess } from "@/lib/permissions";
import { KanbanBoard, type BoardTask } from "@/components/tasks/kanban-board";
import { TaskPanel } from "@/components/tasks/task-panel";
import { Avatar } from "@/components/shared/avatar";
import { formatDateOnly } from "@/lib/date-only";
import { updateProjectAction } from "@/app/actions/domain";

export default async function ProjectPage({ params, searchParams }: { params: Promise<{ workspaceId: string; projectId: string }>; searchParams: Promise<{ view?: string; task?: string; status?: string; priority?: string; assignee?: string; q?: string }> }) {
  const { workspaceId, projectId } = await params; const query = await searchParams;
  const { session, membership, project } = await requireProjectAccess(workspaceId, projectId);
  const [tasks, members, labels, activities] = await Promise.all([
    db.task.findMany({ where: { projectId }, orderBy: [{ status: "asc" }, { position: "asc" }], include: { assignees: { include: { user: true } }, labels: { include: { label: true } } } }),
    db.workspaceMember.findMany({ where: { workspaceId }, include: { user: true }, orderBy: { joinedAt: "asc" } }),
    db.label.findMany({ where: { workspaceId }, orderBy: { name: "asc" } }),
    db.activity.findMany({ where: { projectId }, take: 50, orderBy: { createdAt: "desc" }, include: { actor: true, task: true } }),
  ]);
  const selectedTask = query.task ? await db.task.findFirst({ where: { id: query.task, projectId }, include: { assignees: true, labels: true, comments: { include: { author: true }, orderBy: { createdAt: "desc" } }, links: { orderBy: { createdAt: "desc" } }, activities: { include: { actor: true }, orderBy: { createdAt: "desc" }, take: 20 } } }) : null;
  const boardTasks: BoardTask[] = tasks.map((task) => ({ id: task.id, title: task.title, status: task.status, priority: task.priority, dueDate: task.dueDate?.toISOString() || null, assignees: task.assignees.map((a) => ({ id: a.user.id, name: a.user.name, color: a.user.avatarColor })), labels: task.labels.map((l) => ({ id: l.label.id, name: l.label.name, color: l.label.color })) }));
  const view = ["list", "activity", "links"].includes(query.view || "") ? query.view! : "board";
  const filteredTasks = tasks.filter((task) => (!query.status || task.status === query.status) && (!query.priority || task.priority === query.priority) && (!query.assignee || task.assignees.some((item) => item.userId === query.assignee)) && (!query.q || task.title.toLocaleLowerCase("pl").includes(query.q.toLocaleLowerCase("pl"))));
  const tabs = [{ id: "board", label: "Tablica", icon: Columns3 }, { id: "list", label: "Lista", icon: List }, { id: "activity", label: "Aktywność", icon: Activity }, { id: "links", label: "Linki", icon: Link2 }];
  return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-2">{project.archivedAt && <span className="flex items-center gap-1 rounded-lg bg-[#eeeeea] px-2 py-1 text-xs"><Archive size={12} />Archiwum</span>}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{project.name}</h1><p className="mt-1 max-w-2xl text-[#777772]">{project.description || "Projekt bez opisu"}</p>{["OWNER", "ADMIN"].includes(membership.role) && !project.archivedAt && <details className="mt-3"><summary className="cursor-pointer text-sm font-medium text-orange-600">Edytuj projekt</summary><ActionForm action={updateProjectAction.bind(null,workspaceId,projectId)} className="mt-3 grid max-w-xl gap-2 rounded-xl bg-white p-3 shadow-sm"><input required minLength={2} maxLength={80} name="name" defaultValue={project.name} className="rounded-lg border border-[#deded9] px-3 py-2"/><textarea name="description" defaultValue={project.description||""} maxLength={10000} rows={2} className="rounded-lg border border-[#deded9] px-3 py-2"/><button className="justify-self-start rounded-lg bg-[#252525] px-3 py-2 text-sm text-white">Zapisz</button></ActionForm></details>}</div><div className="flex items-center gap-3"><div className="flex -space-x-2">{members.slice(0, 4).map((member) => <Avatar key={member.userId} name={member.user.name} color={member.user.avatarColor} />)}{members.length > 4 && <span className="grid size-9 place-items-center rounded-full border-2 border-white bg-[#eeeeca] text-xs">+{members.length - 4}</span>}</div>{["OWNER", "ADMIN"].includes(membership.role) && <Link href={`/w/${workspaceId}/team`} className="flex items-center gap-2 rounded-xl border border-[#e4e4df] bg-white px-4 py-2.5 text-sm font-semibold"><Users size={16} />Zaproś</Link>}</div></header>
    <nav className="mt-7 flex gap-1 overflow-x-auto border-b border-[#ececea]">{tabs.map((tab) => <Link key={tab.id} href={`/w/${workspaceId}/projects/${projectId}?view=${tab.id}`} className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-medium ${view === tab.id ? "border-orange-500 text-orange-600" : "border-transparent text-[#777772] hover:text-[#252525]"}`}><tab.icon size={16} />{tab.label}</Link>)}</nav>
    <div className="mt-5 overflow-x-auto">{view === "board" && <KanbanBoard workspaceId={workspaceId} projectId={projectId} initialTasks={boardTasks} readOnly={Boolean(project.archivedAt)} />}{view === "list" && <><form className="mb-4 flex min-w-[720px] flex-wrap gap-2"><input type="hidden" name="view" value="list"/><input name="q" defaultValue={query.q} placeholder="Szukaj po tytule" className="rounded-xl border border-[#deded9] bg-white px-3 py-2 text-sm"/><select name="status" defaultValue={query.status||""} className="rounded-xl border border-[#deded9] bg-white px-3 py-2 text-sm"><option value="">Każdy status</option><option value="TODO">Do zrobienia</option><option value="IN_PROGRESS">W trakcie</option><option value="DONE">Ukończone</option></select><select name="priority" defaultValue={query.priority||""} className="rounded-xl border border-[#deded9] bg-white px-3 py-2 text-sm"><option value="">Każdy priorytet</option><option value="LOW">Niski</option><option value="MEDIUM">Średni</option><option value="HIGH">Wysoki</option><option value="URGENT">Pilny</option></select><select name="assignee" defaultValue={query.assignee||""} className="rounded-xl border border-[#deded9] bg-white px-3 py-2 text-sm"><option value="">Każdy przypisany</option>{members.map((item)=><option key={item.userId} value={item.userId}>{item.user.name}</option>)}</select><button className="rounded-xl bg-[#252525] px-4 py-2 text-sm font-medium text-white">Filtruj</button></form><TaskList tasks={filteredTasks} workspaceId={workspaceId} projectId={projectId} /></>}{view === "activity" && <ActivityFeed activities={activities} />}{view === "links" && <ProjectLinks projectId={projectId} workspaceId={workspaceId} />}</div>
    {selectedTask && <TaskPanel workspaceId={workspaceId} projectId={projectId} task={selectedTask} members={members} labels={labels} currentUserId={session.user.id} role={membership.role} readOnly={Boolean(project.archivedAt)} />}
  </div>;
}

function TaskList({ tasks, workspaceId, projectId }: { tasks: any[]; workspaceId: string; projectId: string }) { return <div className="overflow-hidden rounded-2xl border border-[#ececea] bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fafaf8] text-[#777772]"><tr><th className="p-4">Zadanie</th><th>Status</th><th>Priorytet</th><th>Termin</th><th>Przypisani</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className="border-t border-[#efefec] hover:bg-orange-50/30"><td className="p-4 font-medium"><Link href={`/w/${workspaceId}/projects/${projectId}?view=list&task=${task.id}`}>{task.title}</Link></td><td>{statusLabel(task.status)}</td><td>{priorityLabel(task.priority)}</td><td>{formatDateOnly(task.dueDate)}</td><td>{task.assignees.map((a: any) => a.user.name).join(", ") || "—"}</td></tr>)}</tbody></table>{!tasks.length && <p className="p-10 text-center text-[#848484]">Brak zadań.</p>}</div>; }
function ActivityFeed({ activities }: { activities: any[] }) { return <div className="max-w-3xl rounded-2xl border border-[#ececea] bg-white p-5">{activities.map((item) => <div key={item.id} className="flex gap-4 border-b border-[#f0f0ed] py-4 last:border-0"><Avatar name={item.actor.name} color={item.actor.avatarColor} /><div><p className="text-sm"><strong>{item.actor.name}</strong> · {item.action.toLowerCase().replaceAll("_", " ")}</p>{item.task && <p className="mt-1 text-sm text-[#777772]">{item.task.title}</p>}<time className="mt-1 block text-xs text-[#999994]">{item.createdAt.toLocaleString("pl-PL")}</time></div></div>)}{!activities.length && <p className="py-8 text-center text-[#848484]">Aktywność pojawi się po pierwszej zmianie.</p>}</div>; }
async function ProjectLinks({ projectId, workspaceId }: { projectId: string; workspaceId: string }) { const links = await db.taskLink.findMany({ where: { task: { projectId } }, include: { task: true, createdBy: true }, orderBy: { createdAt: "desc" } }); return <div className="max-w-4xl rounded-2xl border border-[#ececea] bg-white p-5">{links.map((link) => <div key={link.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#f0f0ed] py-4 last:border-0"><div><a href={link.url} target="_blank" rel="noopener noreferrer" className="font-medium text-orange-700">{link.title}</a><p className="text-sm text-[#777772]">{link.task.title} · {link.createdBy.name}</p></div><Link className="text-sm" href={`/w/${workspaceId}/projects/${projectId}?task=${link.taskId}`}>Otwórz zadanie</Link></div>)}{!links.length && <p className="py-8 text-center text-[#848484]">Brak linków w projekcie.</p>}</div>; }
function statusLabel(value: string) { return value === "TODO" ? "Do zrobienia" : value === "IN_PROGRESS" ? "W trakcie" : "Ukończone"; }
function priorityLabel(value: string) { return ({ LOW: "Niski", MEDIUM: "Średni", HIGH: "Wysoki", URGENT: "Pilny" } as Record<string,string>)[value]; }
