import { ActionForm } from "@/components/shared/action-form";
import Link from "next/link";
import { Activity, Archive, Columns3, Link2, List, Users } from "lucide-react";
import type { Prisma } from "@/generated/prisma/client";
import { db } from "@/lib/db";
import { requireProjectAccess } from "@/lib/permissions";
import { KanbanBoard, type BoardTask } from "@/components/tasks/kanban-board";
import { TaskPanel } from "@/components/tasks/task-panel";
import { Avatar } from "@/components/shared/avatar";
import { formatDateOnly } from "@/lib/date-only";
import { updateProjectAction } from "@/app/actions/domain";
import { boardFilterCount, boardFilterParams, filterBoardTasks, parseBoardFilters, type BoardFilterQuery } from "@/lib/board-filters";
import { BoardFiltersForm } from "@/components/tasks/board-filters";
import { ProgressMetrics } from "@/components/dashboard/progress-metrics";
import { countTaskMetrics } from "@/lib/progress-metrics";

type ProjectTask = Prisma.TaskGetPayload<{ include: { assignees: { include: { user: true } }; labels: { include: { label: true } }; checklistItems: { select: { isCompleted: true } } } }>;
type ProjectActivity = Prisma.ActivityGetPayload<{ include: { actor: true; task: true } }>;

export default async function ProjectPage({ params, searchParams }: { params: Promise<{ workspaceId: string; projectId: string }>; searchParams: Promise<{ view?: string; task?: string; status?: string; priority?: string; assignee?: string; q?: string } & BoardFilterQuery> }) {
  const { workspaceId, projectId } = await params; const query = await searchParams;
  const { session, membership, project } = await requireProjectAccess(workspaceId, projectId);
  const [tasks, members, labels, activities] = await Promise.all([
    db.task.findMany({ where: { projectId }, orderBy: [{ status: "asc" }, { position: "asc" }], include: { assignees: { include: { user: true } }, labels: { include: { label: true } }, checklistItems: { select: { isCompleted: true } } } }),
    db.workspaceMember.findMany({ where: { workspaceId }, include: { user: true }, orderBy: { joinedAt: "asc" } }),
    db.label.findMany({ where: { workspaceId }, orderBy: { name: "asc" } }),
    db.activity.findMany({ where: { projectId }, take: 50, orderBy: { createdAt: "desc" }, include: { actor: true, task: true } }),
  ]);
  const selectedTask = query.task ? await db.task.findFirst({ where: { id: query.task, projectId }, include: { assignees: true, labels: true, checklistItems: { orderBy: [{ position: "asc" }, { id: "asc" }] }, comments: { include: { author: true }, orderBy: { createdAt: "desc" } }, links: { orderBy: { createdAt: "desc" } }, activities: { include: { actor: true }, orderBy: { createdAt: "desc" }, take: 20 } } }) : null;
  const today = new Date(); today.setUTCHours(0, 0, 0, 0);
  const taskMetrics = countTaskMetrics(tasks, today);
  const boardTasks: BoardTask[] = tasks.map((task) => ({ id: task.id, title: task.title, status: task.status, priority: task.priority, dueDate: task.dueDate?.toISOString() || null, checklist: { completed: task.checklistItems.filter((item) => item.isCompleted).length, total: task.checklistItems.length }, assignees: task.assignees.map((a) => ({ id: a.user.id, name: a.user.name, color: a.user.avatarColor })), labels: task.labels.map((l) => ({ id: l.label.id, name: l.label.name, color: l.label.color })) }));
  const boardFilters = parseBoardFilters(query);
  const activeBoardFilters = boardFilterCount(boardFilters);
  const boardFilterQuery = boardFilterParams(boardFilters).toString();
  const visibleBoardTasks = filterBoardTasks(boardTasks, boardFilters, new Date().toISOString().slice(0, 10));
  const view = ["list", "activity", "links"].includes(query.view || "") ? query.view! : "board";
  const filteredTasks = tasks.filter((task) => (!query.status || task.status === query.status) && (!query.priority || task.priority === query.priority) && (!query.assignee || task.assignees.some((item) => item.userId === query.assignee)) && (!query.q || task.title.toLocaleLowerCase("pl").includes(query.q.toLocaleLowerCase("pl"))));
  const tabs = [{ id: "board", label: "Tablica", icon: Columns3 }, { id: "list", label: "Lista", icon: List }, { id: "activity", label: "Aktywność", icon: Activity }, { id: "links", label: "Linki", icon: Link2 }];
  return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-2">{project.archivedAt && <span className="flex items-center gap-1 rounded-lg bg-[#eeeeea] px-2 py-1 text-xs"><Archive size={12} />Archiwum</span>}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{project.name}</h1><p className="mt-1 max-w-2xl text-[#777772]">{project.description || "Projekt bez opisu"}</p>{["OWNER", "ADMIN"].includes(membership.role) && !project.archivedAt && <details className="mt-3"><summary className="cursor-pointer text-sm font-medium text-orange-600">Edytuj projekt</summary><ActionForm action={updateProjectAction.bind(null,workspaceId,projectId)} className="mt-3 grid max-w-xl gap-2 rounded-xl bg-white p-3 shadow-sm"><label className="text-sm font-medium">Nazwa projektu<input required minLength={2} maxLength={80} name="name" defaultValue={project.name} className="tf-input mt-1 w-full"/></label><label className="text-sm font-medium">Opis projektu<textarea name="description" defaultValue={project.description||""} maxLength={10000} rows={2} className="tf-input mt-1 w-full"/></label><button className="justify-self-start rounded-lg bg-[#252525] px-3 py-2 text-sm text-white">Zapisz</button></ActionForm></details>}</div><div className="flex items-center gap-3"><div className="flex -space-x-2">{members.slice(0, 4).map((member) => <Avatar key={member.userId} name={member.user.name} color={member.user.avatarColor} />)}{members.length > 4 && <span className="grid size-9 place-items-center rounded-full border-2 border-white bg-[#eeeeca] text-xs">+{members.length - 4}</span>}</div>{["OWNER", "ADMIN"].includes(membership.role) && <Link href={`/w/${workspaceId}/team`} className="flex items-center gap-2 rounded-xl border border-[#e4e4df] bg-white px-4 py-2.5 text-sm font-semibold"><Users size={16} />Zaproś</Link>}</div></header>
    <div className="mt-6"><ProgressMetrics title="Postęp projektu" counts={taskMetrics.counts} overdue={taskMetrics.overdue} lastActivity={activities[0]?.createdAt.toLocaleString("pl-PL", { timeZone: "Europe/Warsaw" })} /></div>
    <nav aria-label="Widoki projektu" className="mt-7 flex flex-wrap gap-x-1 border-b border-[var(--border)]">{tabs.map((tab) => <Link key={tab.id} href={`/w/${workspaceId}/projects/${projectId}?view=${tab.id}`} aria-current={view === tab.id ? "page" : undefined} className={`flex min-h-11 items-center gap-2 border-b-2 px-3 py-2 text-sm font-medium sm:px-4 ${view === tab.id ? "border-[var(--accent)] text-[var(--accent-ink)]" : "border-transparent text-[#55554f] hover:text-[var(--foreground)]"}`}><tab.icon size={16} aria-hidden="true" />{tab.label}</Link>)}</nav>
    <div className="mt-5">{view === "board" && <><BoardFiltersForm projectPath={`/w/${workspaceId}/projects/${projectId}`} filters={boardFilters} members={members.map((member) => ({ userId: member.userId, name: member.user.name }))} labels={labels} resultCount={visibleBoardTasks.length} totalCount={boardTasks.length} /><div className="max-w-full overflow-x-auto"><KanbanBoard workspaceId={workspaceId} projectId={projectId} initialTasks={visibleBoardTasks} readOnly={Boolean(project.archivedAt)} filtersActive={activeBoardFilters > 0} filterQuery={boardFilterQuery} /></div></>}{view === "list" && <><form className="mb-4 grid gap-2 sm:flex sm:flex-wrap"><input type="hidden" name="view" value="list"/><label className="sr-only" htmlFor="task-list-query">Szukaj po tytule</label><input id="task-list-query" name="q" defaultValue={query.q} placeholder="Szukaj po tytule" className="tf-input text-sm"/><label className="sr-only" htmlFor="task-list-status">Status</label><select id="task-list-status" name="status" defaultValue={query.status||""} className="tf-input text-sm"><option value="">Każdy status</option><option value="TODO">Do zrobienia</option><option value="IN_PROGRESS">W trakcie</option><option value="DONE">Ukończone</option></select><label className="sr-only" htmlFor="task-list-priority">Priorytet</label><select id="task-list-priority" name="priority" defaultValue={query.priority||""} className="tf-input text-sm"><option value="">Każdy priorytet</option><option value="LOW">Niski</option><option value="MEDIUM">Średni</option><option value="HIGH">Wysoki</option><option value="URGENT">Pilny</option></select><label className="sr-only" htmlFor="task-list-assignee">Przypisany</label><select id="task-list-assignee" name="assignee" defaultValue={query.assignee||""} className="tf-input text-sm"><option value="">Każdy przypisany</option>{members.map((item)=><option key={item.userId} value={item.userId}>{item.user.name}</option>)}</select><button className="rounded-xl bg-[#252525] px-4 py-2 text-sm font-medium text-white">Filtruj</button></form><TaskList tasks={filteredTasks} workspaceId={workspaceId} projectId={projectId} query={query} /></>}{view === "activity" && <ActivityFeed activities={activities} />}{view === "links" && <ProjectLinks projectId={projectId} workspaceId={workspaceId} />}</div>
    {selectedTask && <TaskPanel workspaceId={workspaceId} projectId={projectId} view={view} boardFilterQuery={boardFilterQuery} searchParams={query} task={selectedTask} members={members} labels={labels} currentUserId={session.user.id} role={membership.role} readOnly={Boolean(project.archivedAt)} />}
  </div>;
}

function TaskList({ tasks, workspaceId, projectId, query }: { tasks: ProjectTask[]; workspaceId: string; projectId: string; query: { status?: string; priority?: string; assignee?: string; q?: string } }) { const href = (taskId: string) => { const params = new URLSearchParams({ view: "list", task: taskId }); for (const key of ["status", "priority", "assignee", "q"] as const) if (query[key]) params.set(key, query[key]); return `/w/${workspaceId}/projects/${projectId}?${params}`; }; return <div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-white"><table className="hidden w-full text-left text-sm md:table"><thead className="bg-[var(--muted-surface)] text-[#55554f]"><tr><th className="p-4">Zadanie</th><th>Status</th><th>Priorytet</th><th>Termin</th><th>Przypisani</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className="border-t border-[var(--border)] hover:bg-orange-50/30"><td className="p-4 font-medium"><Link className="tf-text-link" href={href(task.id)}>{task.title}</Link></td><td>{statusLabel(task.status)}</td><td>{priorityLabel(task.priority)}</td><td>{formatDateOnly(task.dueDate)}</td><td>{task.assignees.map((a) => a.user.name).join(", ") || "—"}</td></tr>)}</tbody></table><div className="divide-y divide-[var(--border)] md:hidden">{tasks.map((task) => <Link key={task.id} href={href(task.id)} className="block p-4 hover:bg-[var(--muted-surface)]"><span className="font-semibold">{task.title}</span><span className="mt-2 block text-sm text-[var(--muted)]">{statusLabel(task.status)} · {priorityLabel(task.priority)} · {formatDateOnly(task.dueDate)}</span><span className="mt-1 block text-xs text-[var(--muted)]">{task.assignees.map((a) => a.user.name).join(", ") || "Bez przypisania"}</span></Link>)}</div>{!tasks.length && <p className="p-10 text-center text-[var(--muted)]">Brak zadań pasujących do wybranych kryteriów.</p>}</div>; }
function ActivityFeed({ activities }: { activities: ProjectActivity[] }) { return <div className="max-w-3xl rounded-2xl border border-[#ececea] bg-white p-5">{activities.map((item) => <div key={item.id} className="flex gap-4 border-b border-[#f0f0ed] py-4 last:border-0"><Avatar name={item.actor.name} color={item.actor.avatarColor} /><div><p className="text-sm"><strong>{item.actor.name}</strong> · {item.action.toLowerCase().replaceAll("_", " ")}</p>{item.task && <p className="mt-1 text-sm text-[#777772]">{item.task.title}</p>}<time className="mt-1 block text-xs text-[#999994]">{item.createdAt.toLocaleString("pl-PL")}</time></div></div>)}{!activities.length && <p className="py-8 text-center text-[#848484]">Aktywność pojawi się po pierwszej zmianie.</p>}</div>; }
async function ProjectLinks({ projectId, workspaceId }: { projectId: string; workspaceId: string }) { const links = await db.taskLink.findMany({ where: { task: { projectId } }, include: { task: true, createdBy: true }, orderBy: { createdAt: "desc" } }); return <div className="max-w-4xl rounded-2xl border border-[#ececea] bg-white p-5">{links.map((link) => <div key={link.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#f0f0ed] py-4 last:border-0"><div><a href={link.url} target="_blank" rel="noopener noreferrer" className="font-medium text-orange-700">{link.title}</a><p className="text-sm text-[#777772]">{link.task.title} · {link.createdBy.name}</p></div><Link className="text-sm" href={`/w/${workspaceId}/projects/${projectId}?task=${link.taskId}`}>Otwórz zadanie</Link></div>)}{!links.length && <p className="py-8 text-center text-[#848484]">Brak linków w projekcie.</p>}</div>; }
function statusLabel(value: string) { return value === "TODO" ? "Do zrobienia" : value === "IN_PROGRESS" ? "W trakcie" : "Ukończone"; }
function priorityLabel(value: string) { return ({ LOW: "Niski", MEDIUM: "Średni", HIGH: "Wysoki", URGENT: "Pilny" } as Record<string,string>)[value]; }
