import Link from "next/link";
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { pl } from "date-fns/locale";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { db } from "@/lib/db";
import { requireWorkspaceMember } from "@/lib/permissions";

export default async function CalendarPage({ params, searchParams }: { params: Promise<{ workspaceId: string }>; searchParams: Promise<{ month?: string; day?: string }> }) {
  const { workspaceId } = await params; const query = await searchParams; await requireWorkspaceMember(workspaceId);
  const current = /^\d{4}-\d{2}$/.test(query.month || "") ? new Date(`${query.month}-01T12:00:00`) : new Date();
  const start = startOfWeek(startOfMonth(current), { weekStartsOn: 1 }); const end = endOfWeek(endOfMonth(current), { weekStartsOn: 1 });
  const tasks = await db.task.findMany({ where: { project: { workspaceId, archivedAt: null }, dueDate: { gte: start, lte: end } }, include: { project: true }, orderBy: { dueDate: "asc" } });
  const byDay = new Map<string, typeof tasks>(); tasks.forEach((task) => { const key = task.dueDate!.toISOString().slice(0, 10); byDay.set(key, [...(byDay.get(key) || []), task]); });
  const monthParam = (date: Date) => format(date, "yyyy-MM"); const selected = query.day ? byDay.get(query.day) || [] : [];
  return <div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">Kalendarz</h1><p className="mt-2 text-[#777772]">Terminy zadań w aktywnych projektach.</p></div><div className="flex items-center gap-2"><Link aria-label="Poprzedni miesiąc" href={`?month=${monthParam(subMonths(current,1))}`} className="rounded-xl bg-white p-2"><ChevronLeft /></Link><strong className="min-w-40 text-center capitalize">{format(current, "LLLL yyyy", { locale: pl })}</strong><Link aria-label="Następny miesiąc" href={`?month=${monthParam(addMonths(current,1))}`} className="rounded-xl bg-white p-2"><ChevronRight /></Link></div></div><div className="mt-6 overflow-hidden rounded-2xl border border-[#ececea] bg-white"><div className="grid grid-cols-7 bg-[#fafaf8] text-center text-xs font-semibold text-[#777772]">{["Pon","Wt","Śr","Czw","Pt","Sob","Nie"].map((d) => <div key={d} className="p-3">{d}</div>)}</div><div className="grid grid-cols-7">{eachDayOfInterval({ start, end }).map((day) => { const key = format(day,"yyyy-MM-dd"); const items = byDay.get(key) || []; const inMonth = day.getMonth() === current.getMonth(); return <Link href={`?month=${monthParam(current)}&day=${key}`} key={key} className={`min-h-24 border-t border-r border-[#f0f0ed] p-2 hover:bg-orange-50/30 ${!inMonth ? "text-[#bbb]" : ""}`}><span className="text-xs">{format(day,"d")}</span><div className="mt-2 space-y-1">{items.slice(0,2).map((task) => <p key={task.id} className="truncate rounded-md bg-orange-50 px-1.5 py-1 text-[10px] text-orange-800">{task.title}</p>)}{items.length > 2 && <p className="text-[10px]">+{items.length-2}</p>}</div></Link>; })}</div></div>{query.day && <section className="mt-6 rounded-2xl border border-[#ececea] bg-white p-5"><h2 className="font-semibold">Zadania: {query.day}</h2><div className="mt-3 space-y-2">{selected.map((task) => <Link key={task.id} href={`/w/${workspaceId}/projects/${task.projectId}?task=${task.id}`} className="block rounded-xl p-3 hover:bg-[#fafaf8]"><strong>{task.title}</strong><p className="text-sm text-[#777772]">{task.project.name}</p></Link>)}{!selected.length && <p className="text-sm text-[#777772]">Brak zadań tego dnia.</p>}</div></section>}</div>;
}
